<?php

namespace OCA\JournalNotes\Vendor;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInitJournalNotes
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('OCA\\JournalNotes\\Vendor\\Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('OCA\JournalNotes\Vendor\ComposerAutoloaderInitJournalNotes', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \OCA\JournalNotes\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('OCA\\JournalNotes\\Vendor\\ComposerAutoloaderInitJournalNotes', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\OCA\JournalNotes\Vendor\Composer\Autoload\ComposerStaticInitJournalNotes::getInitializer($loader));
        $loader->register(\true);
        $filesToLoad = \OCA\JournalNotes\Vendor\Composer\Autoload\ComposerStaticInitJournalNotes::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
